### ISSUE TITLE
add logs directory

### ISSUE THREAD

**Issue by colindaven** [mtmcgowan/masterBLASTer#2]
Quite a nice tool. Only got it working after tracking down using scontrol a missing log file in the subdirectory logs. logs did not exist, so I created it.

Jobs were failing without an error message prior to this, so it might pay to add the logs subdir to the repo ?

cheers.

**Comment by mtmcgowan** [comment]
Thanks! I'll change it so it will check for a log directory and create one if needed. I think that should fix the problem.
